name: tests
on:
  push:
    branches: [ main, master ]
    paths-ignore: [ "**.md" ]
  pull_request:
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate debugging enabled'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: "${{ matrix.bats_tag }} (ddev ${{ matrix.ddev_version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ddev_version: [stable]
        bats_tag: [php83, php84]
    steps:
      - name: ${{ matrix.bats_tag }}
        uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}
          test_command: bats ./tests/test.bats --filter-tags ${{ matrix.bats_tag }}
