#!/bin/bash
#ddev-generated
# pre-start (host) hook: choose how lsphp runs for the project's PHP version.
#   native  - lsphp installed in the web container (Debian trixie: PHP 8.1-8.5)
#   sidecar - lsphp in a Debian-bookworm sidecar container (PHP 7.4, 8.0, which
#             trixie no longer ships)
# Only EOL versions use the code-mount sidecar, so modern PHP has no extra
# container and no macOS/Windows bind-mount slowdown.
#
# Update the case list below if DDEV's web-image Debian release changes which
# lsphp versions are available natively.
set -eu

APPROOT="${DDEV_APPROOT:?DDEV_APPROOT not set}"
COMPOSE="${APPROOT}/.ddev/docker-compose.openlitespeed-lsphp.yaml"
MARKER="# generated by ddev-openlitespeed (sync-lsphp-mode.sh)"

PHPVER="$(sed -nE 's/^php_version:[[:space:]]*"?([0-9]+\.[0-9]+)"?.*/\1/p' "${APPROOT}/.ddev/config.yaml" | head -1)"

case "${PHPVER}" in
  8.1|8.2|8.3|8.4|8.5) MODE=native ;;
  7.4|8.0)             MODE=sidecar ;;
  *)
    echo "ddev-openlitespeed: PHP ${PHPVER:-<unknown>} is not supported (no lsphp package exists)." >&2
    echo "Supported: 7.4, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5. Switch with e.g.: ddev config --php-version=8.3" >&2
    exit 1 ;;
esac

if [ "${MODE}" = "sidecar" ]; then
  # Generated, not committed. DDEV substitutes the ${...} vars when it merges
  # docker-compose.*.yaml. (No #ddev-generated marker: DDEV warns about that in
  # docker-compose.*.yaml files it did not itself generate.)
  #
  # The environment block gives the sidecar the DDEV vars PHP frameworks read
  # from their DDEV settings file (e.g. WordPress wp-config-ddev.php / Drupal
  # settings.ddev.php gate on IS_DDEV_PROJECT and read DDEV_* / DB_*). Without
  # it those files early-return and the app has no DB credentials. DDEV_APPROOT
  # is hardcoded to the in-container path (not the host ${DDEV_APPROOT}).
  cat > "${COMPOSE}" <<CMP
${MARKER}
services:
  openlitespeed-lsphp:
    container_name: ddev-\${DDEV_SITENAME}-openlitespeed-lsphp
    hostname: openlitespeed-lsphp
    build:
      context: openlitespeed/lsphp-sidecar
      args:
        DDEV_PHP_VERSION: \${DDEV_PHP_VERSION}
    user: "\${DDEV_UID}:\${DDEV_GID}"
    labels:
      com.ddev.site-name: \${DDEV_SITENAME}
      com.ddev.approot: \${DDEV_APPROOT}
    restart: "no"
    expose:
      - "9000"
    volumes:
      - "\${DDEV_APPROOT}:/var/www/html"
    environment:
      - IS_DDEV_PROJECT=true
      - DDEV_APPROOT=/var/www/html
      - DDEV_COMPOSER_ROOT=/var/www/html
      - DDEV_DOCROOT=\${DDEV_DOCROOT}
      - DDEV_PRIMARY_URL=\${DDEV_PRIMARY_URL}
      - DDEV_HOSTNAME=\${DDEV_HOSTNAME}
      - DDEV_PROJECT=\${DDEV_PROJECT}
      - DDEV_SITENAME=\${DDEV_SITENAME}
      - DDEV_TLD=\${DDEV_TLD}
      - DDEV_PHP_VERSION=\${DDEV_PHP_VERSION}
      - DDEV_DATABASE=\${DDEV_DATABASE}
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=db
      - DB_PASSWORD=db
CMP
else
  # native: remove any stale generated sidecar compose from a previous 7.4/8.0 run
  if [ -f "${COMPOSE}" ] && head -1 "${COMPOSE}" | grep -qF "${MARKER}"; then
    rm -f "${COMPOSE}"
  fi
fi
